name: 发布版本

on:
  workflow_dispatch:
    inputs:
      tag:
        description: '发布标签'
        required: true
      branch:
        description: '目标分支（用于版本文件更新）'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4.1.0
        with:
          ref: ${{ github.event.inputs.branch }}
          token: ${{ secrets.PAT }}
          
      - name: 获取版本
        id: get_version
        run: |
          echo "date=$(date +%Y%m%d)" >> "$GITHUB_OUTPUT"

      - name: 更新update.json和module.prop
        run: |
          echo '{
            "version": "${{ github.event.inputs.tag }}",
            "versionCode": "${{ steps.get_version.outputs.date }}",
            "zipUrl": "https://github.com/boxproxy/box/releases/download/${{ github.event.inputs.tag }}/box_${{ github.event.inputs.tag }}.zip",
            "changelog": "https://github.com/boxproxy/box/raw/master/CHANGELOG.md"
          }' > update.json

          sed -i "s/$(grep -oP 'version=\K[^ ]+' module.prop)/${{ github.event.inputs.tag }}/g" module.prop
          sed -i "s/$(grep -oP 'versionCode=\K[^ ]+' module.prop)/$(date +%Y%m%d)/g" module.prop
          
      - name: 提交更新的文件
        run: |
          git config --local user.name "GitHub Actions"
          git config --local user.email "actions@github.com"
          git add update.json module.prop
          
          # 检查是否有变更需要提交
          if git diff --staged --quiet; then
            echo "没有文件变更，跳过提交步骤"
          else
            git commit -m "发布 ${{ github.event.inputs.tag }}"
            git push origin ${{ github.event.inputs.branch }}
          fi
 
      - name: 运行build.sh
        run: |
          sh build.sh
          ls -la
          
      - name: 设置输出文件名
        id: set_filename
        run: |
          if ls box_*.zip 1> /dev/null 2>&1; then
            echo "filename_pattern=box_*.zip" >> "$GITHUB_OUTPUT"
          elif ls box-*.zip 1> /dev/null 2>&1; then
            echo "filename_pattern=box-*.zip" >> "$GITHUB_OUTPUT"
          elif ls box_${{ github.event.inputs.tag }}.zip 1> /dev/null 2>&1; then
            echo "filename_pattern=box_${{ github.event.inputs.tag }}.zip" >> "$GITHUB_OUTPUT"
          elif ls box-${{ github.event.inputs.tag }}.zip 1> /dev/null 2>&1; then
            echo "filename_pattern=box-${{ github.event.inputs.tag }}.zip" >> "$GITHUB_OUTPUT"
          else
            echo "filename_pattern=*.zip" >> "$GITHUB_OUTPUT"
          fi
          echo "找到匹配的文件模式: ${{ steps.set_filename.outputs.filename_pattern }}"

      - name: 创建GitHub发布
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.event.inputs.tag }}
          files: ${{ steps.set_filename.outputs.filename_pattern }}
          generate_release_notes: true
          token: ${{ secrets.PAT }}

